title: SmartSolve Blog
email: your@email.com
description: >
  Backlink SEO and tips from SmartSolveTips.com
baseurl: ""
url: "https://sintukobir.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
